name: CI Pipeline
on: [workflow_dispatch]

steps:
  - name: Checkout
    uses: actions/checkout@v6

  - name: Install Rust
    uses: dtolnay/rust-toolchain@stable
    with:
      toolchain: stable
      components: clippy

  - name: Cache
    uses: Swatinem/rust-cache@v2

  - name: Lint
    run: cargo clippy --workspace -- -D warnings

  - name: Test
    run: cargo test --release --workspace

  - name: Build
    run: cargo build --release --workspace
